<?php

return [
    'workspace_root' => env('WORKSPACE_ROOT', '/data/workspaces'),
    'ai_gateway_url' => rtrim((string) env('AI_GATEWAY_URL', 'https://freellmapi.ai101.eu.org'), '/'),
    'ai_gateway_api_key' => env('AI_GATEWAY_API_KEY'),
    'ai_gateway_model' => env('AI_GATEWAY_MODEL'),
    'ai_gateway_timeout' => (int) env('AI_GATEWAY_TIMEOUT', 90),
    'ai_tool_mode' => env('AI_TOOL_MODE', 'auto'),
    'ai_max_iterations' => (int) env('AI_MAX_ITERATIONS', 8),
    'agent_type' => env('AGENT_TYPE', 'studio'),
    'sandbox_driver' => env('SANDBOX_DRIVER', 'local'),
    'sandbox_image' => env('SANDBOX_IMAGE', 'openwrt-ai-agent:latest'),
    'sandbox_host_workspace_root' => env('SANDBOX_HOST_WORKSPACE_ROOT') ?: env('WORKSPACE_ROOT', '/data/workspaces'),
    'sandbox_memory' => env('SANDBOX_MEMORY', '512m'),
    'sandbox_cpus' => env('SANDBOX_CPUS', '1'),
    'sandbox_timeout' => (int) env('SANDBOX_TIMEOUT', 20),
    'openhands_url' => rtrim((string) env('OPENHANDS_URL', ''), '/'),
    'openhands_session_key' => env('OPENHANDS_SESSION_KEY'),
    'default_openwrt_revision' => env('OPENWRT_REVISION', '24.10'),
    'build_driver' => env('BUILD_DRIVER', 'stub'),
    'build_buildroot_image' => env('BUILD_BUILDROOT_IMAGE', 'openwrt-ai-buildroot:24.10'),
    'openwrt_cache_root' => env('OPENWRT_CACHE_ROOT', '/data/openwrt'),
    'openwrt_dl_root' => env('OPENWRT_DL_ROOT', '/data/downloads-cache'),
    'openwrt_ccache_root' => env('OPENWRT_CCACHE_ROOT', '/data/ccache'),
    'openwrt_host_cache_root' => env('OPENWRT_HOST_CACHE_ROOT'),
    'openwrt_host_dl_root' => env('OPENWRT_HOST_DL_ROOT'),
    'openwrt_host_ccache_root' => env('OPENWRT_HOST_CCACHE_ROOT'),
    'studio_host_root' => env('STUDIO_HOST_ROOT'),
    'build_cpus' => (int) env('BUILD_CPUS', 2),
    'build_memory' => env('BUILD_MEMORY', '1g'),
    'build_timeout' => (int) env('BUILD_TIMEOUT', 600),
    'build_firmware_cpus' => (int) env('BUILD_FIRMWARE_CPUS', 4),
    'build_firmware_memory' => env('BUILD_FIRMWARE_MEMORY', '8g'),
    'build_firmware_timeout' => (int) env('BUILD_FIRMWARE_TIMEOUT', 7200),
    'build_sdk_memory' => env('BUILD_SDK_MEMORY', '3g'),
    'build_sdk_timeout' => (int) env('BUILD_SDK_TIMEOUT', 1200),
    'artifact_store' => env('ARTIFACT_STORE', 'local'),
    'minio_endpoint' => env('MINIO_ENDPOINT', 'http://minio:9000'),
    'minio_access_key' => env('MINIO_ROOT_USER'),
    'minio_secret_key' => env('MINIO_ROOT_PASSWORD'),
    'minio_bucket' => env('MINIO_BUCKET', 'artifacts'),
    'queue_workers' => (int) env('QUEUE_WORKERS', 2),
    'quota_workspaces' => (int) env('QUOTA_WORKSPACES', 20),
    'quota_builds_per_hour' => (int) env('QUOTA_BUILDS_PER_HOUR', 20),
    'quota_global_running' => (int) env('QUOTA_GLOBAL_RUNNING', 4),
    'quota_workspace_bytes' => (int) env('QUOTA_WORKSPACE_BYTES', 2147483648),
];
